# Launch
version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: jenkins
    hostname: jenkins
    build:
      dockerfile: ./DockerfileJenkins
      context: .
    restart: always
    environment:
      - HTTP_PORT=8080
    ports:
      - 8078:8080
      - 50058:50000
    volumes:
      - jenkins:/var/jenkins_home
  nexus:
    container_name: sonatype_nexus
    image: sonatype/nexus3
    hostname: sonatype_nexus
    restart: always
    ports:
      - 8076:8081
    volumes: 
      - nexus-data:/nexus-data

volumes:
  jenkins:
    driver: local
  nexus-data:
    driver: local